apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sn-system
  name: connectorcatalogs-reader-sn-users
rules:
  - apiGroups: ["example.com"]
    resources: ["connectorcatalogs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connectorcatalogs-reader-sn-users-binding
  namespace: sn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: connectorcatalogs-reader-sn-users
subjects:
  - kind: ServiceAccount
    name: sn-users-sa
    namespace: sn-users