apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sn-users
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: sn-users
subjects:
  - kind: ServiceAccount
    name: sn-users-sa
    namespace: sn-users
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io